name: vania_cli
description: A Command-Line Interface for Vania dart web application to create new projects, controllers, models, migrations, middlewares, build and serve Vania project
version: 0.0.4+2
repository: https://github.com/vania-dart/vania_cli
homepage: https://vdart.dev
documentation: https://vdart.dev/docs/intro
topics: [server, backend, httpserver, framework, web]


environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  path: ^1.9.0
  watcher: ^1.1.0  

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0

executables:
  vania: vania_cli